name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*"  # Triggers the workflow only on push of tags starting with 'v'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      MOD_NAME: ''
      MOD_VERSION: ''
      MOD_JAR: ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare environment value
        run: |
          MOD_NAME=$(grep 'archives_base_name=' gradle.properties | cut -d'=' -f2)
          MOD_VERSION=$(grep 'mod_version=' gradle.properties | cut -d'=' -f2)
          
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          echo "MOD_JAR=$MOD_NAME-$MOD_VERSION.jar" >> $GITHUB_ENV
          echo "MOD_SOURCE_JAR=$MOD_NAME-$MOD_VERSION-sources.jar" >> $GITHUB_ENV

      - name: Build mod
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}  # Ensure this step runs only if previous steps succeeded
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.MOD_VERSION }}
          name: "Release v.${{ env.MOD_VERSION }}"
          draft: false
          prerelease: false
          files: |
            ./build/libs/${{ env.MOD_JAR }}
            ./build/libs/${{ env.MOD_SOURCE_JAR }}
