name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow only on push of tags starting with 'v'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Read mod name from gradle.properties
        id: read_mod_name
        run: |
          # Read the mod name from gradle.properties
          MOD_NAME=$(grep 'archives_base_name=' gradle.properties | cut -d'=' -f2)
          echo "MOD_NAME=MOD_NAME" >> $GITHUB_ENV

      - name: Build the mod
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: true

      - name: Upload Jar to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/${{ env.MOD_NAME }}-${{ github.ref_name }}.jar
          asset_name: ${{ env.MOD_NAME }}-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
